### PR TITLE
Add Property ID, Item_Relations ID, and Subject / Object ItemTitles

### PR DESCRIPTION
**Pull request by milnerm**
Add Property ID, Item_Relations ID, and Subject / Object Item Titles to API JSON

Essentially these are named graphs, they should have the resource ID, as well as the property ID for the relation itself. If the relation has labels, so should the subject and object, for consistency

### CODE REVIEW

**Comment by milnerm** [comment]
I understand a client of ours may have discussed this PR in a meeting with @zerocrates this past week. If there could be a review, that'd be great, though I suspect timelines aren't necessarily lining up. 
I can deploy the changes above here in our version of the plugin, and can adjust as any edits / requests for changes are discussed.

**Comment by zerocrates** [comment]
I guess I'd start with a broad question of what's the use-case underlying these additions? I'm not opposed to making the API here more convenient to consume and/or more functional, but I wouldn't necessarily add, for example, IDs to everything for consistency's sake alone.

Simple stuff: the style is for 4-space indentation, not tabs, so if you could switch those that would be great.

Do you have a need for the `item_relation` entry? It doesn't really fit the API to do it that way (those arrays that indicate type and a URL/ID are used for links to related resources, not the resource itself. IDs of the relation entries themselves are somewhat of an internal detail which is why they aren't currently included, not that there's necessarily a problem to do so if it's useful for some purpose. The same comment applies to the ID for the relation term/property.

On consistency, the label of the relation term is provided only because Item Relations allows custom relations, which are only really identifiable by their labels. I can see the titles of the related items being useful... I'm assuming a goal of this PR is to avoid having to make additional requests to look up titles for the related items? At any rate, I think rather than consistency with the property label, these should be keyed as "title" as that's what's being gotten here.

It looks to me like your code for looking up the titles does not handle the case where the related items on either side of the relation are missing or unable to be read by the current user. Have you checked this? Those `get_record_by_id` calls can return null.

**Comment by milnerm** [comment]
Thanks for the comments. I've done the following:

- tabs are now 4 spaces
- subject and object labels are now 'titles'

In terms of the more conceptual issues:
- yes, the intent is to limit the number of calls to the API. With these changes this plugin can now be used to render simple D3JS network graph visualizations, and save calls doing so.
- I think there's a bit of a mismatch in the API design intent then here, as what you're suggesting is more of a view of relations ontologically as a matter of category, But in fact what is stored and evident here is a quad or named graph. IE, the relation itself IS an entity / object, has an id property, and therefore is unique. It's odd that the itemrelation model *wouldn't* have the object's id listed in the API call. On that note, if, like the other API representations for objects the primary data were prioritized, and the subjet, relation, object were seen as attributes of the itemRelation object / entity / record itself, then the JSON might be better presented as below, but this could create backwards compatibility issues.

`return array(
    'item_relation' => array(
        'id' => $record->id,
        'resource' => 'item_relations',
        'subject' => array(
            'id' => $record->subject_item_id,
            'url' => self::getResourceUrl("/items/{$record->subject_item_id}"),
            'title' => ItemRelationsPlugin::getItemTitle($subject),
        'resource' => 'items',
        ),
        'relation' => array(
                'id' => $record->property_id,
                'term' => $term,
                'label' => $record->property_label,
                'vocabulary' => $record->vocabulary_name,
        ),
        'object' => array(
                'id' => $record->object_item_id,
                'url' => self::getResourceUrl("/items/{$record->object_item_id}"),
                'title' => ItemRelationsPlugin::getItemTitle($object),
                'resource' => 'items',
        )
    )
);`

Basically, it just seems some key data is missing, and making additional API calls when elements can be added to the representation is a useful solution.

Lastly - could definitely control for when related items are missing or unable to be read - but this raises the question for the plugin in general: why, if one of the items is null or missing, or permissions aren't set on the record, would the relation itself be regarded as valid data? shouldn't this kind of data consistency / integrity be caught elsewhere? if it's simply a matter of error catching, something could be added above prior to the rendering of the representation, and return false or null as per API specs. But what's the design principle on those kinds of scenarios? Are missing items caught elsewhere in item api models?

Happy to push revisions to this when I hear back.

**Comment by milnerm** [comment]
Updated the revisions - can you have a look?

**Comment by zerocrates** [comment]
I'll take a look next week.

**Comment by zerocrates** [comment]
Indentation change looks fine, as does the change to `title`.

If you want to include `id` for the relation then it should go as a top-level key, sibling to subject/relation/object. It's kind of like your commented example, but without the extra `item_relation` outer containing key. That kind of "container" doesn't really add anything and doesn't match the rest of the API. As for whether you _should_ include them: the relations have IDs more or less because everything has IDs, but we don't always expose those in the API. Absent a specific use case for the ID to be added my inclination would be to leave it out still; with a use case I don't particularly mind its inclusion.

In either case the "resource" key is unnecessary in this context and doesn't match the rest of the API, so it should be excluded.

Those two points taken together: consider just not including the relation ID. If you're going to include it, make it just a top-level key. Don't include a `item_relation` key or `resource` key.

On checking for null items: I was initially thinking of the case where the subject and/or object are private items that can't be seen by the current user, but the plugin takes care of that itself by excluding those in the query stage. I'd still just in the realm of "belt and suspenders" have a quick check against null for those to output a null title just to avoid the possibility of a fatal error if the item can't be retrieved. A simple ternary like `$subject ? ItemRelationsPlugin::getItemTitle($subject) : null` would do fine.

**Comment by milnerm** [comment]
Client has returned to have this work done, so returning to it myself.
The use case for the relation id is simple: it's an edge in graph theory, and should be identified as an element. An id makes it easier to control when the same edge appears in the data. For network graph visualizations, this simply helps manage the data more consistently. 

In terms of the item_relation itself, we're also back to some graph theory - but I think we can work with the sibling approach for sure. It acts then as a named graph / quad.

Please see the latest revisions.

**Comment by zerocrates** [comment]
Okay... I'm happy with what you've got here now. Thanks for bearing with me on the changes.

**Pull request merged**
